checks:
  qbittorrent:
    info: qbittorrent client
    group: Media
    command: |
      ps -ef | grep -E '([q]bittorrent)'
  minidlna:
    info: UPnP server (pictures/videos)
    group: Media
    command: |
      ps -ef | grep -E '([m]inidlna)'
  Steam:
    info: Steam Games Desktop Client
    group: Media
    command: |
      ps -ef | grep -E '([s]team.sh)'
  vi:
    group: Tools
    indicators:
      positive:
        status: editor in use
        icon: ğŸ’¡
      negative:
        status: editor not in use.
        icon: âš«
    command: |
      ps -ef | grep -E "pts.* [v]i($| .*)"
    sub_checks:
      Memory Usage:
        command: |
          ps --no-headers -o rss -C vi | awk '{sum+=$1} END {printf "%.2f MB (%.2f GB)\n", sum/1024, sum/1048576}'
  Data Backup:
    info: My custom backup orchestration solution
    indicators:
      positive:
        status:
          icon: âœ…
      negative:
        status:
          icon: âŒ
    group: Backup
    command: |
      stat ~/.jbl-backup.log | grep ^Modify
  ExpressVPN:
    info: For general privacy and security.
    group: Security
    indicators:
      positive:
        icon: ğŸ”‘
      negative:
    command: |
      expressvpn status | grep -i connected | sed "s/\\x1b\\[[0-9;]*[mGK]//g"
    sub_checks:
      Updates:
        command: |
          expressvpn status | grep update | sed "s/\\x1b\\[[0-9;]*[mGK]//g"
        indicators:
          positive:
            status: Update Available!
            icon: ğŸ’¡
          negative:
            status: No update available.
            icon: âš«
  Dropbox:
    group: Mount
    indicators:
      positive:
        icon: ğŸ“‚
      negative:
        icon: ğŸ“‚
    command: |
      ps -ef | grep [d]ropbox
    info: Monitoring that dropbox process is running
  KeepassXC:
    group: Security
    command: |
      ps -ef | grep -i '[b]in/keepassxc'
  Apache NiFi:
    group: Data
    command: |
      ps -ef | grep -i '[o]pt/nifi'
  Open WebUI:
    group: Data  # Updated to Data group
    command: |
      curl localhost:3000 --silent | grep '<title>' | sed -e 's/^.*title>Open WebUI.*$/Open WebUI/'
  Galaxy S20 (sshfs):
    indicators:
      positive:
        icon: ğŸ“² 
        status: is mounted
      negative:
        icon: ğŸ“±
        status: is not mounted
    group: Mount
    command: |
      mount | grep -i '/mnt/GalaxyS20'
  sshd:
    group: Security
    command: |
      ps -ef | grep -E '([s]shd)'
  Midnight Commander:
    indicators:
      positive:
        status: is running.
        icon: ğŸ’¡
      negative:
        icon: âš«
        status: is not running.
    group: Tools
    command: |
      ps -ef | grep "\ mc$"
  tmux:
    indicators:
      positive:
        status: is running.
        icon: ğŸ’¡
      negative:
        status: is not running.
        icon: âš«
    group: Tools
    command: |
      ps -ef | grep "\ tmux$"
  dockerd:
    group: Virtualization
    command: |
      ps -ef | grep -E "[/]usr/bin/dockerd"
  signal-desktop:
    group: Security
    command: |
      ps -ef | grep -E "[/]opt/Signal/signal-desktop"
  Thunderbird:
    info: My favorite mail client
    group: Communications
    indicators:
      positive:
        status:
        icon: ğŸ“§
      negative:
        status:
        icon: ğŸ“§
    command: |
      ps -ef | grep -E "[t]hunderbird"
    sub_checks:
      Memory Usage:
        command: |
          ps --no-headers -o rss -C thunderbird | awk '{sum+=$1} END {printf "%.2f MB (%.2f GB)\n", sum/1024, sum/1048576}'
        indicators:
          positive:
              icon: ğŸ’¾
          negative:
              icon: ğŸ’¾
      Version:
        command: |
          thunderbird --version
  CUPS:
    info: CUPS print service
    group: Media
    command: |
      ps -ef | grep -E "[c]ups"
